<?php
$headlines = array(
  "Google Apps Login and Admin Console Down",
  "If It Ain't Broke, Don't Fix It: Ancient Computers in Use Today",
  "Pirate Bay co-founder charged with hacking and fraud",
  "Google Outage",
  "Google Apps Admin Console Down",
  "What happened to Japan's electronic giants?",
  "1-on-1 meetings with your Team",
  "What happens when you give 4chan images of the Boston Marathon?",
  "BTC bubbles",
  "Space Monkey: Taking the cloud out of the datacenter",
  "Share live code snippets in your browser",
  "Tus - an Open Source File Upload Protocol",
  "A Comparison of Angular, Backbone, CanJS and Ember",
  "DotScale, the tech conference to supersize your apps in Paris, June 7",
  "Ember.js - Web Applications Done Right",
  "Profiling using DTrace - Tutorial Part1",
  "EFF Politely Asks PTO to Stop Issuing So Many Crappy Software Patents",
  "Data journalism busts speeding cops, wins Pulitzer",
  "Circuits.io's biggest feature release to date: multi-layered PCBs and much more",
  "Denotational Semantics: A Methodology for Language Development [book] [scribd]",
  "10,000 Startups opens for Application",
  "Criminal Sketch Artist Draws Women as They See Themselves and as Others See Them",
  "What is probabilistic programming?",
  "HN Meetup, Bangalore",
  "The key to a great work ethic? Glucose",
  "1Password GPU brute-force with 3M hash/s",
  "Foxconn Becomes Largest Microsoft Patent Licensee",
  "Let people pay you. Make it easy",
  "Researchers Finally Replicated Reinhart-Rogoff, and There Are Serious Problems",
  "The best QBasic game ever?",
  "Trigger.io one year on",
  "Show HN: Sparklin Wars, multiplayer Web shooter I built over 2 nights",
  "Silk Road Founder Says Bitcoin Booms And Busts Won't Kill His Black Market",
  "Parallella, a $99 Linux Supercomputer",
  "The bomb that changed my life",
  "Your First iOS App – 100% Programmatically",
  "Physicists To Test If Universe Is A Computer Simulation",
  "Explosions near Boston Marathon finish line",
  "The Oh-My-God particle",
  "If I Made Another Monkey Island...",
  "New GitHub Logo",
  "The Boston Marathon Bombing: Keep Calm and Carry On",
  "Ask HN: Any Moscow HNers?",
  "Gitmo Is Killing Me",
  "Categories – What’s the Point?",
  "Linode hacked, CCs and passwords leaked",
  "Teaching the Essentials of Garbage Collection",
  "How Damaged Are NFL Players' Brains?",
  "What is the rule for adjective order?",
  "All American Airlines Flights Grounded, Experiencing Nationwide Computer Outage",
  "HN Meetup, New Delhi",
  "Applicants wanted for a one way ticket to Mars",
  "If you're in Boston without phone service, use this website to call your family",
  "Security incident update",
  "Mike Pall: Ramblings on languages and architectures",
  "There is No Right Way to Develop Software",
  "I've created a community and learning platform for math, physics and CS lovers",
  "Facebook Home prototyped in Quartz Composer",
  "Show HN: Pinterest for text",
  "Webcam Pulse Detector",
  "Build Your Own SaaS Using Docker",
  "The Dangers of Thinking Like an Economist",
  "Twitter is forcing us to drop ability to flattr creators by favoriting tweets",
  "Buy Stamps from Your Command Line",
  "Fergulator - NES emulator, written in Go",
  "Xamarin Test Cloud",
  "Cool illustration of RGB color mixing in LaTeX",
  "Fat startup: Learn the lessons of my failed Lean Startup",
  "OKCupid starts accepting Bitcoin using Coinbase",
  "Lessons Learned Raising a $6 Million Round",
  "Buyer sued for posting factual negative review on eBay",
  "Reinhart-Rogoff Response to Critique",
  "Why your games are made by childless, 31 year old white men",
  "Google Glass API Documentation",
  "Tell HN: YC rejection emails have started going out",
  "Moot v1.1",
  "Virgil: a statically-typed language balancing functional and OO features",
  "A nonpartisan, independent review concludes U.S. Engaged in Torture After 9/11",
  "Build Cross-Platform Apps in C# using Parse and Xamarin",
  "Singapore startup Nitrous.IO raises USD 1M round from Silicon Valley investors",
  "How To Build Apps In C#, WinForms and ASP.NET Using Mono In Raspberry Pi",
  "A Better Development Workflow with Vagrant",
  "Comprehensive Immigration Bill set to be Unveiled",
  "Person Finder: Boston Marathon Explosions",
  "News is bad for you – and giving up reading it will make you happier",
  "Data for the Boston Marathon Investigation Will Be Crowdsourced",
  "The little things I learned from the Valley",
  "The Node.js Community is Quietly Changing the Face of Open Source",
  "Scaling Pinterest - From 0 to 10s of Billions of Page Views a Month in Two Years",
  "How much usage can a Lego piece take before it loses its 'clutch power'?",
  "Ask HN: Can we help the police sort through the photos of the Boston Marathon?",
  "The Terrifying Reality of Long-Term Unemployment",
  "SMS-First Startups",
  "HTML5 Video at Netflix",
  "Bob's wife Carla lends a speedy mind",
  "Firebase Adds PhoneGap Integration",
  "The people we're leaving behind",
  "The Well Deserved Fortune of Satoshi, Bitcoin creator, Visionary and Genius",
  "Writing Python in Scheme",
  "_why's print spool client",
  "Recorded mouse positions replayed over music video [NSFW]",
  "Packery, a JavaScript layout library",
  "Google Affiliate Network Shutting Down",
  "Core libraries stabilize with Dart's new M4 release",
  "Moqups Premium",
  "HN: To all the rejected",
  "Mozilla TowTruck – real-time collaboration on any site",
  "_why's site is updated",
  "PyCon 2013 Coding Challenge Roundup",
  "Yelp extorting small businesses",
  "Left-Handedness Stumps Science",
  "Applicants wanted for a one way ticket to Mars",
  "JIT CPU Emulation: A 6502 to x86 Dynamic Recompiler",
  "Coupling in Object-Oriented Programming",
  "Inequality And New York’s Subway",
  "_why's site updated again",
  "Tests Are Overhyped",
  "MRI's Method Caches",
  "Dustforce sales figures",
  "How to Use the Git Protocol Through a HTTP CONNECT Proxy",
  "Intel Profits Fall as PC Slump Cuts Demand for Chips",
  "Ask HN: Why doesn't PG do a responsive version of HN?",
  "Glass developers prohibited from displaying ads, charging for software",
  "Stack Exchange is winning the Internet and this is not a good thing",
  "Perl in Javascript",
  "Putin unveils $50 billion drive for Russian space supremacy",
  "Google Affiliate Network is shutting down",
  "B2B Startups Cloudant and Clustrix Enter Y Combinator Index Top 10",
  "Microsoft scores biggest patent licensee yet: China’s Foxconn",
  "xkcd: Authorization",
  "CanvasJS HTML5 and JavaScript Charts",
  "Reimplementing 'git clone' in Haskell from the bottom up",
  "Bitcoin: Whatever It Is, It's Not Money",
  "Show HN: AngelExcel - A place to organize your fundraising efforts",
  "Space: A whitespace alternative to JSON",
  "Relationships are more important than ambition",
  "Startup Brazil: Brazilian government is doing a startup program, too",
  "New immigration proposals revealed - More H1-B Visas, but also start-up Visa",
  "Ask HN: How much, on average, do freelancers make?",
  "Nitrous.IO",
  "Sex Machine: Get gender from first name in Ruby",
  "Raygun.io adds crash reporting support for Windows Phone 7.1 & 8",
  "Simulation of landmine clearing with Massoud Hassani's Mine Kafon",
  "7 Reasons to Hack",
  "Fuduntu Linux is closing its doors",
  "The Best Startup Advice I've Ever Gotten"
);

if (array_key_exists('n', $_REQUEST)) {
  $n = $_REQUEST['n'];
} else {
  $n = 1;
}

$results = array();

for ($j=0; $j<$n; ++$j) {
  $i = rand(0, count($headlines)-1);
  array_push($results, $headlines[$i]);
}

header('Content-type: application/json');

print json_encode($results);
